# Generated by Django 3.0.7 on 2020-06-12 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.TimeField()),
                ('number', models.IntegerField(default=60)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('gender', models.CharField(default='male', max_length=200)),
                ('time', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.Train')),
            ],
        ),
    ]
